clc;
clear all;
close all;
xn=input('Enter the x(n) sequence');
hn=input('Enter the h(n) sequence');
LHS=conv(xn,hn);
disp('LHS=');
disp(LHS);
RHS=conv(hn,xn);
disp('RHS=');
disp(RHS);
L=length(xn);
n=0:1:L-1;
subplot(2,2,1);
stem(n,xn);
xlabel('Time index');
ylabel('Amplitude');
title('Input x(n)sequence');
M=length(hn);
n1=0:1:M-1;
subplot(2,2,2);
stem(n1,hn);
xlabel('Time index');
ylabel('Amplitude');
title('Input h(n)sequence');
P=length(LHS);
n2=0:1:P-1;
subplot(2,2,3);
stem(n2,LHS);
xlabel('Time index');
ylabel('Amplitude');
title('LHS sequence');
Q=length(RHS);
n3=0:1:Q-1;
subplot(2,2,4);
stem(n3,RHS);
xlabel('Time index');
ylabel('Amplitude');
title('RHS sequence');
