clc;
clear all;
close all;
xn=input('Enter the x(n) sequence');
yn=input('Enter the y(n) sequence');
rxy=xcorr(xn,yn);
disp('cross correlation output');
disp(rxy);
L=length(xn);
n=0:1:L-1;
subplot(2,2,1);
stem(n,xn);
xlabel('Time index');
ylabel('Amplitude');
title('Input x(n) sequence');
M=length(yn);
n1=0:1:M-1;
subplot(2,2,2);
stem(n1,yn);
xlabel('Time index');
ylabel('Amplitude');
title('Input y(n)sequence');
N=length(rxy);
n2=0:1:N-1;
subplot(2,2,3);
stem(n2,rxy);
xlabel('Time index');
ylabel('Amplitude');
title('Output rxy sequence');