clc;
clear all;
close all;
wpa=input('Enter the pass band frequency');
wsa=input('Enter the stop band frequency');
wsp=input('Enter the sampling frequency');
wpd=2*pi*wpa/wsp;
wsd=2*pi*wsa/wsp;
td=wsd-wpd;
N=ceil(6.6*pi/td);
wc=wsd+wpd/2;
wc=wc/pi;
hw=hamming(N);
stem(hw);
figure(1);
title('Hamming coefficients');
hn=fir1(N,wc,hamming(N+1));
disp(hn);
[m,w]=freqz(hn,1,128);
mag=20*log10(abs(m));
figure(2);
plot(wsp*w/(2*pi),mag);
title('FIR filter');