clc;
clear all;
close all;
a=input('Enter the Numerator coefficients');
b=input('Enter the Denominator coefficients');
hn=impz(a,b,5);
disp(hn);
L=length(a);
n=0:1:L-1;
subplot(2,2,1);
stem(n,a);
xlabel('Time index');
ylabel('Amplitude');
title('Input numerator sequence');
M=length(b);
n1=0:1:M-1;
subplot(2,2,2);
stem(n1,b);
xlabel('Time index');
ylabel('Amplitude');
title('Input dinominator sequence');
N=length(hn);
n2=0:1:N-1;
subplot(2,2,3);
stem(n2,hn);
xlabel('Time index');
ylabel('Amplitude');
title('Output impulse sequence');