clc;
clear all;
close all;
xn=input('Enter the x(n)sequence');
hn=input('Enter the h(n)sequence');
yn=conv(xn,hn);
disp(yn);
k=length(xn);
n=0:1:k-1;
subplot(2,2,1);
stem(n,xn);
xlabel('Time index');
ylabel('Amplitude');
title('Input x(n)sequence');
v=length(hn);
n1=0:1:v-1;
subplot(2,2,2);
stem(n1,hn);
xlabel('Time index');
ylabel('Amplitude');
title('Input h(n)sequence');
N=length(yn);
n2=0:1:N-1;
subplot(2,2,3);
stem(n2,yn);
xlabel('Time index');
ylabel('Amplitude');
title('Output sequence');