clc;
clear all;
close all;
x1=input('Enter the x1(n)sequence');
x2=input('Enter the x2(n)sequence');
a1=1;
a2=1;
y1=a1*x1+a2*x2;
LHS=fft(y1);
disp('LHS=');
disp(LHS);
y2=fft(x1);
y3=fft(x2);
RHS=a1.*y2+a2*y3;
disp('RHS=');
disp(RHS);
if(LHS==RHS)
disp('Linearity property is proved');
else
disp('Linearity property is not proved');
end
L=length(x1);
n=0:1:L-1;
subplot(2,2,1);
stem(n,x1);
xlabel('Time index');
ylabel('Amplitude');
title('Input x1 sequence');
M=length(x2);
n1=0:1:M-1;
subplot(2,2,2);
stem(n1,x2);
xlabel('Time index');
ylabel('Amplitude');
title('Input x2 sequence');
P=length(LHS);
n2=0:1:P-1;
subplot(2,2,3);
stem(n,LHS);
xlabel('Time index');
ylabel('Amplitude');
title('LHS sequence');
Q=length(RHS);
n3=0:1:Q-1;
subplot(2,2,4);
stem(n3,RHS);
xlabel('Time index');
ylabel('Amplitude');
title('RHS sequence');
