clc;
clear all;
close all;
xn=input('Enter the input sequence');
N=4;
Xk=fft(xn,N);
disp(Xk);
mag_Xk=abs(Xk);
disp('mag_xk=');
disp(mag_Xk);
phase_Xk=angle(Xk);
disp('phase_xk=');
disp(phase_Xk);
L=length(xn);
n=0:1:L-1;
subplot(2,2,1);
stem(n,xn);
xlabel('Time index');
ylabel('Amplitude');
title('Input x(n) sequence');
M=length(mag_Xk);
n1=0:1:M-1;
subplot(2,2,2);
stem(n1,mag_Xk);
xlabel('Time index');
ylabel('Amplitude');
title('output magnitude');
Q=length(phase_Xk);
n2=0:1:Q-1;
subplot(2,2,3);
stem(n2,phase_Xk);
xlabel('Time index');
ylabel('Amplitude');
title('output phase');
