clc;
clear all;
close all;
x=-pi:0.05:pi;
xn=sinc(x);
X1=fft(xn);
X2=fftshift(X1);
subplot(2,1,1);
plot(xn);
title('Time domain signal');
subplot(2,1,2);
plot(abs(X2));
title('Frequency domain signal');