clc;
clear all;
close all;
xn=[zeros(1,16),ones(1,32),zeros(1,16)];
X1=fft(xn);
X2=fftshift(X1);
subplot(2,1,1);
plot(xn);
title('Time domain square pulse signal');
subplot(2,1,2);
plot(abs(X2));
title('Frequency domain square pulse signal');
